version = 0.1

[default.global.parameters]
region = "us-east-1"

[default.deploy.parameters]
stack_name = "website-smartravels-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
parameter_overrides = "ProjectName=website-smartravels SiteName=smartravels Environment=prod BucketName=smartravelevents-com-prod DomainName=smartravelevents.smartravelevents.com WwwDomainName=www.smartravelevents.smartravelevents.com PriceClass=PriceClass_100"
